/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mainmap.glb 
Author: Pablopcb (https://sketchfab.com/pablopcb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/among-us-map-the-skeld-59a93886f9e74ff6836dff0c269da45f
Title: Among Us - Map "The Skeld"
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mainmap(props) {
  const { nodes, materials } = useGLTF('/models/mainmap.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <mesh geometry={nodes.Object_164.geometry} material={materials.Caja_tex} />
        <mesh geometry={nodes.Object_165.geometry} material={materials.Color_17} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.Groundco} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.PISO_M02} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.TEXTUR01} />
        <mesh geometry={nodes.Object_169.geometry} material={materials.TEXTURA} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.Color_C} />
        <mesh geometry={nodes.Object_171.geometry} material={materials.medicina} />
        <mesh geometry={nodes.Object_172.geometry} material={materials.monito01} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.TEXT_NAV} />
        <mesh geometry={nodes.Object_174.geometry} material={materials.monitor} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.piso_ele} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.pared_ad} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.piso_alm} />
        <mesh geometry={nodes.Object_178.geometry} material={materials.piso_caf} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.piso_cam} />
        <mesh geometry={nodes.Object_180.geometry} material={materials.textu_pi} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.textu_01} />
        <mesh geometry={nodes.Object_182.geometry} material={materials.reacto01} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.test_med} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.text_c01} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.text_com} />
        <mesh geometry={nodes.Object_186.geometry} material={materials.Color_07} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.Color_08} />
        <mesh geometry={nodes.Object_188.geometry} material={materials.Color_16} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.Formica} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['0066_Hon']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['0080_Dar']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['0080_Dar']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['0080_Dar']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['0080_Dar']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['0087_Cya']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['0135_Dar']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Caja_t03} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Caja_t01} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Caja_t02} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Color_A0} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Color_B0} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Color_B0} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Color_B0} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Color_15} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Color_C0} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Color_13} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Color_11} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Color_D0} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Color_D0} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Color_E0} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Color_12} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Color_F0} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Color_04} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Color_H0} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Color_05} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Color_01} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Color_01} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Color_01} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Color_I0} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Color_14} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Color_03} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Color_J0} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Color_06} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Color_10} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Color_K0} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.Color_L0} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Color_L1} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Color_L1} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Color_L1} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Color_09} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.Color_02} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Color_M0} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Color_M0} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.Color_M0} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Color_M0} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Foregrou} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Formic01} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.FrontCol} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Metal_St} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.PISO_MED} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.PISO_M01} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.Quartz_L} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.Transluc} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.Transl01} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.Water_Da} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.Color_B} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.Color02} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.Color_D} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.Color_H} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.Color_H} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.Color_H} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.Color03} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.Color_I} />
        <mesh geometry={nodes.Object_130.geometry} material={materials.Color_M} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.Color_M} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.monito02} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.motores} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.pared_al} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.pared_ca} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.pared_es} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Object_145.geometry} material={materials.piso_com} />
        <mesh geometry={nodes.Object_147.geometry} material={materials.piso_pas} />
        <mesh geometry={nodes.Object_148.geometry} material={materials.piso_p01} />
        <mesh geometry={nodes.Object_150.geometry} material={materials.piso_tex} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.piso_t04} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.piso_t03} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.piso_t01} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.piso_t02} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.reactor} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.separado} />
        <mesh geometry={nodes.Object_163.geometry} material={materials.textura} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mainmap.glb')
